"""Renders `docs/35_excel_workbook.md` from the same objects `build` used to write the workbook.

Every count in the doc is read off the workbook that was just written, so the two cannot drift. The reconciliation
section is filled from `outputs/excel/reconciliation.json`, which `tests/test_excel_reconciliation.py` writes when it
recalculates the file; before the test has ever run, that section says so rather than quoting a stale number.
"""

from __future__ import annotations

import json

from desk import HORIZON_END, SIM_LABEL, WINDOW_END, WINDOW_START
from desk.excel import sheet_readme, sources
from desk.excel.layout import FORMULA, INPUT, KEY, PASTED, Counts
from desk.paths import EXCEL_DIR

RECON_JSON = EXCEL_DIR / "reconciliation.json"


def _table(headers, rows) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def render(counts: Counts, ctx: dict) -> str:
    data: sources.Data = ctx["data"]
    L = []
    L += _intro(data)
    L += _sheets(counts, ctx)
    L += _coverage(counts, ctx)
    L += _interview()
    L += _checks(ctx)
    L += _recon()
    L += _not_in_excel()
    L += _limitations(data)
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------------------------------------ sections
def _intro(data: sources.Data) -> list[str]:
    return [
        "# 35 — Master Excel workbook (`outputs/excel/Metals_Desk_Master.xlsx`)", "",
        f"**{SIM_LABEL}.** Every counterparty, vessel, voyage, bank, survey outcome and payment delay in the "
        "workbook is simulated and its name ends \"(SIM)\". Market series carry the Phase 0 provenance flags "
        "unchanged.", "",
        "_Generated by `desk.excel.build` from the published Phase 0–3 files and the parameter register — do not "
        "hand-edit either the workbook or this page; re-run "
        "`DESK_OFFLINE=1 .venv/bin/python -c \"import desk.excel.build as m; m.main()\"`._", "",
        "## 1. What this is, and what \"formula-driven\" means here", "",
        "MASTER_SPEC Table 8.2 asks for a master Excel workbook that is formula-driven for Components 1–3, with "
        "GARCH, Monte Carlo and credit scoring left in Python. This is that workbook. Because \"formula-driven\" is "
        "a claim a recruiter can test in thirty seconds by changing a cell, it is worth being exact about what is "
        "live and what is not:", "",
        "* **Components 1 and 2 are fully live.** `Parity`, both Table 1.5 sensitivity grids and the Table 1.7 term "
        "structure contain **no computed constants at all** — every line item is an Excel formula reading `Inputs` "
        "and `Market_Weekly`/`Market_Daily`. The trade tickets and counterparties are inputs, which is what they "
        "are in `config/` too; the CONTRACTS §5a eligibility of each ticket is re-tested live against `Parity`.",
        "* **Component 3 is live at the leg level on a declared marking grid.** The FX conversion of every dated "
        "flow, the whole MCX variation- and initial-margin schedule, the FX-forward marks, the unsold-cargo "
        "replacement mark, per-trade cumulative P&L and the book equity curve are formulas. Leg *amounts* that fall "
        "out of the ticket lifecycle are carried from the engine, labelled green and named row by row in "
        "`amount_src` / `value_src`; §7 lists them and says why each one stays in Python.",
        "* **Nothing is a picture.** The equity curve is a native Excel line chart over formula cells.", "",
        f"Window {WINDOW_START} → {WINDOW_END}; engine horizon {HORIZON_END}; panel "
        f"{data.panel['date'].min().date()} → {data.panel['date'].max().date()} "
        f"({len(data.panel)} LME trading days).", "",
        "## 2. What this does and doesn't tell you", "",
        "**It does** let you interrogate the desk's arithmetic without reading Python: change a duty rate, a grade "
        "factor, a freight level or an LME print and watch the import parity, the trade-eligibility flags, the "
        "marks and the P&L move together, with every intermediate line visible. It also shows, cell by cell, that "
        "the workbook and the engine agree — the `Checks` sheet differences them at every grain the workbook "
        "reaches.", "",
        "**It does not** make the numbers more true. A formula inherits the provenance of its inputs: the freight "
        "levels and the lag-2 grade mix are hindsight reconstructions (CONTRACTS §4.3, `scrap_grades.yaml`), the "
        "USD/INR series is an ECB cross standing in for the RBI/FBIL reference rate, and the MCX series is "
        "duty-paid import parity — which is exactly why the cross-exchange basis on this book is **zero by "
        "construction** and the workbook shows that residual as a column rather than claiming a basis it cannot "
        "observe. It is also not a risk system: a spreadsheet that recalculates one state cannot produce a GARCH "
        "volatility path or a 10,000-path P&L distribution, and this one does not pretend to.", "",
    ]


def _sheets(counts: Counts, ctx: dict) -> list[str]:
    rows = []
    for name, part, what in sheet_readme.SHEET_MAP:
        c = counts.per_sheet.get(name, {})
        total = sum(c.values())
        rows.append([f"`{name}`", part, f"{c.get(FORMULA, 0):,}", f"{counts.ratio(name):.0%}" if total else "—",
                     what])
    return ["## 3. Sheet by sheet", "",
            _table(["Sheet", "Part", "Formula cells", "Formula share", "What it is"], rows), "",
            "The formula share is formula cells ÷ all written cells on the sheet, counting row keys, labels, "
            "provenance strings and green check columns in the denominator. A sheet that is mostly a register "
            "(`Inputs`, `Counterparties`, `Trade_Book`) is *supposed* to be mostly input.", ""]


def _coverage(counts: Counts, ctx: dict) -> list[str]:
    rows = []
    tot = {INPUT: 0, FORMULA: 0, PASTED: 0, KEY: 0}
    for name in [s[0] for s in sheet_readme.SHEET_MAP]:
        c = counts.per_sheet.get(name, {})
        for k in tot:
            tot[k] += c.get(k, 0)
        rows.append([f"`{name}`", f"{c.get(FORMULA, 0):,}", f"{c.get(INPUT, 0):,}", f"{c.get(PASTED, 0):,}",
                     f"{c.get(KEY, 0):,}", f"{sum(c.values()):,}"])
    rows.append(["**Total**", f"**{tot[FORMULA]:,}**", f"**{tot[INPUT]:,}**", f"**{tot[PASTED]:,}**",
                 f"**{tot[KEY]:,}**", f"**{sum(tot.values()):,}**"])
    total = sum(tot.values())
    share = tot[FORMULA] / total if total else 0.0
    return ["## 4. Formula coverage", "",
            _table(["Sheet", "formula", "input (blue)", "pasted (green)", "key / label", "total"], rows), "",
            f"**{tot[FORMULA]:,} formula cells of {total:,} written cells ({share:.0%})**, against "
            f"{tot[INPUT]:,} inputs and {tot[PASTED]:,} pasted engine values. Of the pasted cells, roughly half are "
            "pure check columns that nothing depends on; the rest are the carried lifecycle amounts named in §7.", ""]


def _interview() -> list[str]:
    rows = [[t, b] for t, b in sheet_readme.HOW_TO]
    return ["## 5. Using it in an interview", "",
            "Open `Checks` first — the scoreboard at the top is a formula over every block below it, so it cannot be "
            "stale, and it tells the reader in one line whether the workbook still agrees with the engine. Then:", "",
            _table(["Do this", "And it shows"], rows), "",
            "The single best demonstration is the first one: `bcd_scrap_hs7602` 0.025 → 0.05 moves the duty base on "
            "all 258 parity rows, pushes `net_arb_inr_t` down by roughly the duty on the assessable value, flips "
            "`trade_eligible` on the marginal weeks, and turns `Trade_Book!eligible_matches_book` red for any ticket "
            "whose week no longer clears — which is the CONTRACTS §5a discipline rule enforcing itself in front of "
            "the interviewer. Undo the change and everything goes green again.", ""]


def _checks(ctx: dict) -> list[str]:
    rows = [[b["family"], f"{b['n']:,}", b["tolerance"]] for b in ctx["checks"]["blocks"]]
    return ["## 6. The Checks sheet", "",
            _table(["Check family", "Rows", "Tolerance"], rows), "",
            "Each row of each block pastes the engine's value (green), references the workbook's own formula cell, "
            "shows the difference and raises a PASS/FAIL against a tolerance held as a named range on `Inputs`. "
            "The two tolerances the brief fixes are `tol_parity_inr_t` = ₹1 per tonne on every parity line and "
            "`tol_trade_inr` = ₹10 per trade on MTM and cumulative P&L. The others exist because the *published "
            "CSV* rounds: `amount_ccy` to 2 dp (so a re-derived INR amount cannot tie closer than about ₹0.75), "
            "and USD/t and ₹/kg to 4 dp.", "",
            "One control is deliberately indirect and is stated as such on the sheet: the Phase 1 ↔ Phase 3 "
            "replacement-value tie (`R = goods + bcd + sws + port` on every parity **value date**) cannot be made "
            "in the workbook, because the marking grid is month-ends and those are not parity value dates. The "
            "chain is workbook `replacement_inr_t` ↔ engine `px_inr_t` (checked on every `INVENTORY` row here) ↔ "
            "Phase 1 (checked in `pnl_controls.csv`).", ""]


def _recon() -> list[str]:
    head = ["## 7. Reconciliation test", "",
            "`tests/test_excel_reconciliation.py` loads the saved workbook with the `formulas` library and "
            "**recalculates it from the formulas alone**. There is nothing else it could do: openpyxl writes "
            "formulas without cached results, and one of the tests opens the saved zip and asserts that no `<f>` "
            "element is followed by a cached `<v>`. It then asserts four things:", "",
            "1. every `check` cell recalculates to PASS, and so does the scoreboard formula that aggregates them;",
            "2. the computed sheets really are computed — a formula-vs-constant census per sheet against a floor "
            "per sheet, so a later edit cannot quietly swap a formula for a pasted number;",
            "3. no cell recalculates to `#REF!`, `#NAME?`, `#DIV/0!`, `#VALUE!`, `#N/A`, `#NULL!` or `#NUM!`;",
            "4. the workbook is byte-for-byte deterministic (CONTRACTS §1.5) — rebuilding it produces an identical "
            "file, which is why the zip entry timestamps and the document properties are pinned.", ""]
    if not RECON_JSON.exists():
        return head + ["_No reconciliation run has been recorded yet. Run "
                       "`DESK_OFFLINE=1 .venv/bin/python -m pytest -q tests/test_excel_reconciliation.py` and "
                       "re-run `desk.excel.build` to fill this section._", ""]
    r = json.loads(RECON_JSON.read_text())
    rows = [[f"`{k}`", f"{v['formula']:,}", f"{v['constant']:,}", f"{v['ratio']:.0%}"]
            for k, v in sorted(r["sheets"].items())]
    scope = r.get("scope", "full workbook")
    return head + [
        f"**Scope of the recalculation: {scope}.** {r.get('scope_note', '')}", "",
        f"* cells recalculated: **{r['n_recalculated']:,}**  ·  wall time **{r['seconds']:.0f} s**",
        f"* `Checks` cells read: **{r['n_check_cells']:,}**, failures: **{r['n_check_failures']}**",
        f"* scoreboard verdict recalculated from the formulas: **{r['scoreboard']}**",
        f"* error values after recalculation (`#REF!` / `#NAME?` / `#DIV/0!` / `#VALUE!` / `#N/A`): "
        f"**{r['n_errors']}**", "",
        "Formula-vs-constant census of the written cells in the saved file (openpyxl read-back, independent of the "
        "recalculation):", "",
        _table(["Sheet", "formula cells", "constant cells", "formula share"], rows), "",
        "Worst absolute differences the recalculated workbook reports, by family:", "",
        _table(["Check family", "max |difference|", "tolerance", "status"],
               [[k, f"{v['max_abs_diff']:,.4f}", v["tolerance"], v["status"]] for k, v in r["families"].items()]),
        "",
    ]


def _not_in_excel() -> list[str]:
    rows = [[a, b] for a, b in _NOT_IN_EXCEL]
    return ["## 8. What stays in Python, and why", "",
            _table(["Left in Python", "Why"], rows), "",
            "Two of these deserve the longer answer.", "",
            "**The attribution chain.** The engine splits each day's P&L by fully revaluing every leg of every "
            "ticket eight times — once for each `FACTOR_ORDER` block, then for the contracts block — from "
            "yesterday's state to today's, so that cross-terms land in the factor that moves last and the residual "
            "is a genuine control rather than a plug. Reproducing that in cells would mean eight copies of the "
            "whole lifecycle expansion per trade-day. `Attribution` §3a and §3b instead work the chain in full on "
            "two legs whose value is closed form — a short MCX hedge across the day the LME broke from its "
            "all-time high, and a USD payable against the forward that hedges it — and check each step against "
            "`desk.mtm.curves` directly. That shows the mechanism honestly and proves the arithmetic; it does not "
            "claim to be the whole engine.", "",
            "**Leg amounts from the ticket lifecycle.** A purchase invoice on an `LME_M1_AVG` formula is the mean of "
            "the official cash price over the panel days of a quotational month; a quality claim depends on a "
            "survey outcome and a penalty schedule; demurrage counts calendar days of dwell past a free period; an "
            "LC fee runs on a validity computed from a laycan and a presentation period. These are "
            "date-and-contract computations on a rolled panel calendar, not market arithmetic — which is why the "
            "workbook carries the amount and derives everything the *market* does to it (the FX conversion to "
            "settle date, the aggregation into cumulative P&L).", ""]


_NOT_IN_EXCEL = [
    ("GARCH(1,1) VaR, the 10,000-path Monte Carlo, logistic credit scoring",
     "MASTER_SPEC Table 8.2 places them in Python. A spreadsheet version would be a different, worse model wearing "
     "the same name."),
    ("The eight-step sequential attribution, per trade-day",
     "Eight full revaluations of every leg of every ticket, every day. Worked live on two closed-form legs instead "
     "(`Attribution` §3a, §3b), and the published table's identities are re-checked in cells."),
    ("Leg amounts out of the ticket lifecycle",
     "Quotational-period averages, survey outcomes and claim arithmetic, demurrage day counts, LC fee bases. "
     "Carried green and marked `PYTHON_LIFECYCLE`; the market conversion applied to them is a formula."),
    ("Funding accrual",
     "A day-by-day walk of each trade's own dated cash balance at `wc_rate_inr_pa`, including variation margin and "
     "the balance-sheet flows. Carried and labelled on `Equity_Curve` and `MTM_Daily`."),
    ("Every panel day of leg-level MTM",
     "`mtm_daily.csv` is 28,343 rows. The workbook values every open leg on a declared marking grid — month-end "
     "panel days, every trade date, the adverse-event endpoints, `WINDOW_END`, `HORIZON_END` — fixed as a rule in "
     "`desk.excel.sources`, not chosen after seeing results."),
    ("Excel Data Tables for the sensitivity grids",
     "No Python library can evaluate a Data Table, so a Data Table would be a number nobody could check. Each grid "
     "cell instead re-derives the whole CONTRACTS §5 build-up at the shocked market with explicit formulas."),
]


def _limitations(data: sources.Data) -> list[str]:
    return ["## 9. Limitations and open issues", "",
            "1. **The marking grid is not every day.** Leg-level marks exist on "
            f"{len(data.mark_dates)} dates, not on all {data.attribution['date'].nunique()} book days. The "
            "`Equity_Curve` carries the engine's daily open-MTM and re-derives it from `MTM_Daily` only where the "
            "grid reaches; the difference column shows both. Per-trade cumulative P&L is reconciled at "
            "`WINDOW_END` and `HORIZON_END` as the brief requires.",
            "2. **Green cells that feed forward.** The colour convention would be cleaner if nothing downstream "
            "ever depended on a pasted value. It does not hold for the carried lifecycle amounts, so those rows "
            "carry an explicit `amount_src` / `value_src` column rather than relying on the reader to remember.",
            "3. **Rounding floors three of the tolerances.** The workbook reads the published CSVs, which are "
            "rounded for determinism (₹0.01 on money, 4 dp on prices). `tol_cashflow_inr`, `tol_usd_t` and part of "
            "`tol_grid_inr` exist only because of that; `Checks` says so row by row, and the observed differences "
            "sit one to three orders of magnitude inside every tolerance.",
            "4. **Phase 3 book parameters are still served from code.** `config/params/book.yaml` does not exist; "
            "`Inputs` §4 lists the eleven keys the workbook uses from "
            "`desk.mtm.constants.BOOK_PARAM_FALLBACKS`, with their flags and verification status, separately from "
            "the register so the two can never be confused. Three of them carry PENDING verification.",
            "5. **Recalculation is slow outside Excel.** Excel itself recalculates the file instantly; the "
            "`formulas` library takes minutes because it builds an explicit dependency graph over every cell. The "
            "reconciliation test therefore runs as one long test and reports its own wall time.",
            "6. **The workbook inherits every Phase 0 caveat.** Freight levels and the lag-2 grade mix are "
            "hindsight reconstructions; USD/INR is an ECB cross, PENDING a measured comparison against FBIL; the "
            "MCX panel series is import parity, so bucket (b) is zero by construction and the mirror run — which "
            "is the only way to see a real cross-exchange basis — is a Python sensitivity, not a workbook sheet.",
            ""]
